name: Release Version
on:
  push:
    tags:
      - "v*.*.*"

env:
  MATE_DESKTOP_VERSION: 1.28.2
  CACHE_PATH: /tmp/.cache

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Install dependency packages
        run: sudo .github/workflows/ubuntu.sh

      - name: Build the source code
        run: .github/workflows/builds.sh

      - name: Create github release
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes caja-*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
